### PR TITLE
BaSP-MR-80: Classes implement shared components

### PR DESCRIPTION
**Pull request by ghost**
BaSP-MR-80: Classes implement shared components

### CODE REVIEW

**Review by lorenzomauro59 — APPROVED** [review]
Everything works, good job!!

**Comment by lorenzomauro59** [comment]
[[Classes] - Implement the shared components](https://trello.com/c/zdBFQo4U/80-classes-implement-the-shared-components)

**Review by EmaBaldor — APPROVED** [review]
Good job!

**Review by ale-schmidt — APPROVED** [review]
All looks and works great!

**Pull request merged**
