### PR TITLE
BaSP-MR-171: Splitted code with lazy

### PR DESCRIPTION
**Pull request by AleMac17**
Implement lazy in all the routes to split our code

Implement a loader to show when the chunk is loading

Test our application to ensure that lazy loading works correctly and doesn't cause any issues

### CODE REVIEW

**Review by lorenzomauro59 — APPROVED** [review]
Nice job Aleee!

**Review by marcohzo — APPROVED** [review]
Looks great!

**Review by fernandofernandezuy — APPROVED** [review]
Looks great

**Comment by AleMac17** [comment]
[Code Splitting - Lazy](https://trello.com/c/GAtiQMl4/171-code-splitting-lazy)

**Review by EmaBaldor — APPROVED** [review]
The code looks good, good job.

**Pull request merged**
