### PR TITLE
BaSP-MR-70: Added new admin route

### PR DESCRIPTION
**Pull request by EmaBaldor**
Added a new admin form route to add and edit and its corresponding logic.
Route Add: 'admins/form'
Route Edit: 'admins/form/id'

### CODE REVIEW

**Comment by EmaBaldor** [comment]
[[Admin] - Move the logic of the form to the new route](https://trello.com/c/4HjrZPP8/70-admin-move-the-logic-of-the-form-to-the-new-route)

**Review by lorenzomauro59 — APPROVED** [review]
Nice job emaaa!

**Review by fernandofernandezuy — APPROVED** [review]
Good work!

**Comment by araefedg** [comment]
The redirection flow when adding a new admin works correctly!!!! Good work!

**Pull request merged**
