### PR TITLE
BaSP-MR-190: Sign up layout and logic

### PR DESCRIPTION
**Pull request by marcohzo**
- Create a sign-up folder
- Create the layout
- Create logic needed to create a member from the folder's member
- Add JOI validations to the form
- Change the title of the form to 'Sign-up'
- Create the necessary route to access the sign up screen
- Add a button to enter the sign-up in the header

### CODE REVIEW

**Comment by marcohzo** [comment]
[[Sign-up] Layout and Firebase logic](https://trello.com/c/QRSW7ouq/190-sign-up-layout-and-firebase-logic)

**Review by EmaBaldor — APPROVED** [review]
Good Job!

**Review by Gonzarey96 — APPROVED** [review]
This registration form works correctly, good job!

**Review by lorenzomauro59 — APPROVED** [review]
Good job marquito!

**Pull request merged**
