### PR TITLE
BaSP-MR-143: setup-refactorized-business-logic

### PR DESCRIPTION
**Pull request by AleMac17**
Group all entities folders into one Admin folder

Create the logic of the SuperAdmin resource

Create the logic of the Member resource

Configure the absolute imports

Absolute imports for validation, redux, routes

Create example of absolute import (admin-activities)

Add Routes for member

Add Routes for admin

Update logic to select role

### CODE REVIEW

**Review by fernandofernandezuy — APPROVED** [review]
Look great to me!

**Comment by AleMac17** [comment]
[[Setup] - Admin folders](https://trello.com/c/2ssUhYqS/143-setup-admin-folders)

**Review by marcohzo — APPROVED** [review]
Everything looks good!

**Comment by nazarenapantanetti** [comment]
Tested by QA Team, changes requested! Follow the link to see full report: https://trello.com/c/W3eRy6Ci/180-setup-bug

**Pull request merged**
