### PR TITLE
BaSP-MR-127: Super admin PUT POST redux

### PR DESCRIPTION
**Pull request by Federico-Peralta**
- Created the constants, actions and reducer
- Moved the logic PUT and POST to the thunks
- Corrected PUT and POST
- Change the code to use PUT and POST REDUX

### CODE REVIEW

**Review by EmaBaldor — COMMENTED** [review]
You can unify the modals of the superAdmins index into one.

**Review by EmaBaldor — APPROVED** [review]
Good Job!

**Review by marcohzo — APPROVED** [review]
The entire code looks correct

**Comment by Federico-Peralta** [comment]
[[Super Admins] - Move post and put logic](https://trello.com/c/zo5cle6w/127-super-admins-move-post-and-put-logic)

**Comment by nazarenapantanetti** [comment]
Tested in master, approved!

**Pull request merged**
