### PR TITLE
BaSP-MR-76: Button component

### PR DESCRIPTION
**Pull request by lorenzomauro59**
Adds a shared button component with add, confirm/cancel/submit, and edit/delete buttons. Also gives styles with css.

### CODE REVIEW

**Comment by lorenzomauro59** [comment]
[[Shared-Components] Button](https://trello.com/c/Iah3xQDo/76-shared-components-button)

**Review by Federico-Peralta — APPROVED** [review]
Seems good, tested!

**Review by fernandofernandezuy — APPROVED** [review]
Looks good to me!

**Comment by LucreciaV** [comment]
[[Super-Admin] BUG Add/Edit Form](https://trello.com/c/3BjECLTw/96-super-admin-bug-add-edit-form)

**Comment by araefedg** [comment]
Everything seems to be working properly, good job Lorenzo!

**Pull request merged**
