### PR TITLE
BaSP-MR-81: implement shared components (buttons, modals and table) in members, fixed general issues with CSS and remove Modal for confirm edit in Activities

### PR DESCRIPTION
**Pull request by fernandofernandezuy**
In this pull request, I added the shared components Button, Modal, and Table from Components/Shared in the entity Members.

After the planning for week 13 we agree to fix some issues from this PR to speed up the work, I removed general CSS selectors in some files, remove the property min-height: 100vh in the Layout component and remove Modal for confirm edit in Activities

### CODE REVIEW

**Comment by AleMac17** [comment]
[[Members] - Implement the shared components](https://trello.com/c/zQq0YjXv/81-members-implement-the-shared-components)

**Review by lorenzomauro59 — CHANGES_REQUESTED** [review]
You should remove the members/modal folder, and implement new hot-fix styles

**Comment by marcohzo** [comment]
Everything looks correct!

**Review by lorenzomauro59 — APPROVED** [review]

**Review by ale-schmidt — COMMENTED** [review]
I was reading my mates comments and I agree with all of them :)

**Review by Gonzarey96 — CHANGES_REQUESTED** [review]
Trainers must fix.

**Review by Gonzarey96 — APPROVED** [review]
I have checked the whole app after this fix and everything seems to be in order.

**Comment by araefedg** [comment]
Bug Found! leave you a ticket on trello!  https://trello.com/c/SKgBIDZd

**Comment by araefedg** [comment]
Bugs have been fixed! Great work Fer!

**Pull request merged**
