### PR TITLE
BaSP-MR-120: Members redux logic for get and delete - spinner

### PR DESCRIPTION
**Pull request by EmaBaldor**
Added redux logic to get and delete members.
Completed thunks, actions, constans and reducers files.
The spinner was added for when the data is loading.

### CODE REVIEW

**Review by Federico-Peralta — APPROVED** [review]
Tested and seems good

**Review by Gonzarey96 — APPROVED** [review]
The code looks nice, good job!

**Comment by EmaBaldor** [comment]
[[Members] - Move get and delete logic](https://trello.com/c/JQ9bK6IG/120-members-move-get-and-delete-logic)

**Comment by araefedg** [comment]
Hi Ema! everything seems working great! nice job!

**Comment by nazarenapantanetti** [comment]
Tested in master, changes requested! I leave you the link to the full report: https://trello.com/c/1dkIFLMn/155-member-bug-spinner-fails

**Pull request merged**
