### PR TITLE
BaSP-MR-84: Subscriptions implement shared components

### PR DESCRIPTION
**Pull request by marcohzo**
Replace the buttons using the shared component "Button"
Replace the table using the shared component "Table"
Use the shared component "Modal" to display the confirm delete, success message and error message
Fix styles

### CODE REVIEW

**Comment by marcohzo** [comment]
[[Subscriptions] - Implement the shared components](https://trello.com/c/mvN1AVLm/84-subscriptions-implement-the-shared-components)

**Review by ale-schmidt — APPROVED** [review]
I was looking at the code and checking out functionalities and looks awesome for me :)

**Review by lorenzomauro59 — APPROVED** [review]
Everything works!

**Review by Gonzarey96 — APPROVED** [review]
Nice work! approved

**Comment by araefedg** [comment]
Found that a component is missing! leave you a ticket on trello! https://trello.com/c/70cSPqY6

**Comment by araefedg** [comment]
I was testing the new implementations and the bug found was successfully fixed. Great work!

**Pull request merged**
