### PR TITLE
BaSP-MR-194: Add privated routes

### PR DESCRIPTION
**Pull request by ghost**
All React application routes must be updated to make it accessible to the corresponding users, that is, Member routes can only be accessed as long as there is a Member logged into the application, otherwise the application should not allow access to these routes.

### CODE REVIEW

**Comment by ghost** [comment]
[[App] Add privated routes](https://trello.com/c/s0Cf6zMw/194-app-add-privated-routes)

**Comment by fernandofernandezuy** [comment]
When im enter like a super admin and want to edit or add an admin the history.push takes me to the wrong route, great job Dani

**Review by fernandofernandezuy — APPROVED** [review]
Great job Dani!

**Review by Gonzarey96 — APPROVED** [review]
Approved

**Review by lorenzomauro59 — APPROVED** [review]

**Comment by nazarenapantanetti** [comment]
Tested in master and approved!

**Pull request merged**
