### PR TITLE
BaSP-MR-223: Added history feature for subscriptions

### PR DESCRIPTION
**Pull request by Gonzarey96**
-Added a history showing active and inactive subscriptions.
-Date format in the table
-A counter from 0 to 10 in the table title
-Added icon to revert the table based on the date
-Added the ability to filter by date with the search engine.

### CODE REVIEW

**Comment by lorenzomauro59** [comment]
Good job gonzaa! everything works ok!! The only suggestion, it seems that the counter in the table is confusing, it doesn't seem very functional to me, from my point of view I would not put a counter in the table, since it marks a maximum of 10 and sometimes there are more in the complete list

**Review by fernandofernandezuy — CHANGES_REQUESTED** [review]
I agree with Loren, it seems redundant to have the number of items at the head of the table, also with the changes made in this PR you deleted the edit and delete actions for the rest of the entities tables, please revert that.

**Comment by Gonzarey96** [comment]
> I agree with Loren, it seems redundant to have the number of items at the head of the table, also with the changes made in this PR you deleted the edit and delete actions for the rest of the entities tables, please revert that.

The actions of remove, edit and add were not eliminated, only the functionality of hiding the buttons for only views was added and that must be modified in the shared table, it has been fixed so that by default it is set to true (as before).

As for the counter comes as a possible solution to the fact that currently we have no information about the number of items that are in the table, this is becoming a problem in the history that receives items periodically without the possibility of getting rid of them for the moment, the decision was taken in conjunction with other team members and several opinions were consulted on the matter.

**Review by fernandofernandezuy — APPROVED** [review]

**Comment by fernandofernandezuy** [comment]
[[Admin] Subscription](https://trello.com/c/M1oHLEW6/223-admin-subscription)

**Pull request merged**
