### PR TITLE
BaSP-MR-148: Update absolut imports and create consitency between form styles

### PR DESCRIPTION
**Pull request by fernandofernandezuy**
In this pull request, I made changes to improve the code and user experience. 

• Updated the imports from relative paths (e.g., "../../") to absolute paths for better maintainability and readability.

• Replaced in /Admin the "Admins" folder for "Profile" .

• Created consistency between form styles in all sections

• Replace the mode ''onBlur" for "all" in the useForm() in all forms for better ui.

### CODE REVIEW

**Comment by fernandofernandezuy** [comment]
[[ Super Admin - Admin ] Absolute imports and Form Styles](https://trello.com/c/YyYGv5OF/148-super-admin-admin-absolute-imports-and-form-styles)

**Review by lorenzomauro59 — APPROVED** [review]
Everything works ok  !

**Review by ale-schmidt — APPROVED** [review]

**Review by ale-schmidt — APPROVED** [review]
Looks and works great from here, congrats!

**Review by EmaBaldor — APPROVED** [review]
Great job!

**Comment by araefedg** [comment]
💯

**Pull request merged**
