### PR TITLE
BaSP-MR-225: Member login validation

### PR DESCRIPTION
**Pull request by lorenzomauro59**
- Add logic to log in
- Replace alert to toast
- Add message to inform that is not allowed
- Implement toast in log out and log in

### CODE REVIEW

**Review by fernandofernandezuy — APPROVED** [review]
Good Job!

**Comment by lorenzomauro59** [comment]
[[Admin] Member log in](https://trello.com/c/461CpL2h/225-admin-member-log-in)

**Comment by araefedg** [comment]
Hi Loren! implementations are correct, but the toast is repeated in cascade when clicking multiple times in the "login" button, i left you a ticket on Trello: https://trello.com/c/9nKRerdw

**Comment by nazarenapantanetti** [comment]
Bugs reported in card number 230 of Trello, were successfully fixed. https://trello.com/c/w4Q2MyTK/230-login-bug-password-input-is-untidy

**Pull request merged**
