### PR TITLE
BaSP-MR-82: implemented shared components in activity

### PR DESCRIPTION
**Pull request by AleMac17**
Replace the buttons using the shared component /Button

Replace the table using the shared component /Table

Use the shared component /Modal to display the confirm delete, success message and error message

### CODE REVIEW

**Comment by AleMac17** [comment]
[[Activity] - Implement the shared components](https://trello.com/c/Q4L2PwL2/82-activity-implement-the-shared-components)

**Review by lorenzomauro59 — APPROVED** [review]
We fixed styles in collaboration in co-working. everything is well!

**Review by Federico-Peralta — APPROVED** [review]
Seems good!

**Comment by nazarenapantanetti** [comment]
Tested and approved!

**Pull request merged**
