### PR TITLE
BaSP-MR-97: Activity bug "Add new activity" button don't work properly

### PR DESCRIPTION
**Pull request by lorenzomauro59**
I have resolved this bug, ensure that the "Add new activity" button remains functional even after navigating through other activity options such as editing or deleting.

### CODE REVIEW

**Comment by lorenzomauro59** [comment]
[[Activity]-BUG-"Add new activity" button dont work properly](https://trello.com/c/51PJXv9B/97-activity-bug-add-new-activity-button-dont-work-properly)

**Review by fernandofernandezuy — APPROVED** [review]
Looks good to me!

**Comment by nazarenapantanetti** [comment]
Tested in master, same bug was found. Bug report returns to "to do" list. Link to bug report https://trello.com/c/51PJXv9B/97-activity-bug-add-new-activity-button-dont-work-properly

**Comment by nazarenapantanetti** [comment]
Tested and approved! Bug fixed!

**Pull request merged**
