### PR TITLE
BaSP-MR-142: Setup HookForm

### PR DESCRIPTION
**Pull request by fernandofernandezuy**
This pull request adds the necessary dependencies for managing the form and validations in our app:

• React Hook Form: A popular library for managing form state in React applications.
• @hook-form/resolvers: An optional package that provides validation resolver functions for React Hook Form
• Joi: A powerful JavaScript validation library used with @hook-form/resolvers to validate form data.

I also adapt the shared Input component to work with this new dependencies.

### CODE REVIEW

**Comment by fernandofernandezuy** [comment]
[[Setup] - HookForm](https://trello.com/c/5Xq6oDpP/142-setup-hookform)

**Comment by fernandofernandezuy** [comment]
[[Setup] - HookForm](https://trello.com/c/5Xq6oDpP/142-setup-hookform)

**Comment by fernandofernandezuy** [comment]
[[Setup] - HookForm](https://trello.com/c/5Xq6oDpP/142-setup-hookform)

**Review by lorenzomauro59 — APPROVED** [review]

**Review by marcohzo — APPROVED** [review]
Great job!

**Pull request merged**
