### PR TITLE
BaSP-MR-152: [Member] React hook form implementation

### PR DESCRIPTION
**Pull request by Federico-Peralta**
- Create validations for members
- Implemented react form
- Implemented shared input
- Styles corrections

### CODE REVIEW

**Review by Gonzarey96 — APPROVED** [review]
The code is ok, but maybe you should check some styles in the form, for example when showing the blur validations the isActive check is hidden under the submit button, also the check has a bug that does not allow to click correctly.

**Comment by Federico-Peralta** [comment]
[[Members] - React-hook-form implementation](https://trello.com/c/lYh8s5wX/152-members-react-hook-form-implementation)

**Review by EmaBaldor — APPROVED** [review]
Great job!

**Review by marcohzo — APPROVED** [review]
Looks good!

**Comment by LucreciaV** [comment]
left a ticket on trello because of the validations! https://trello.com/c/DXdWJTXm/181-members-bug-react-hook-form-implementation

**Pull request merged**
