### PR TITLE
BaSP-MR-79: Shared table

### PR DESCRIPTION
**Pull request by fernandofernandezuy**
This pull request implements a shared table component to be used in each entity.

### CODE REVIEW

**Review by lorenzomauro59 — APPROVED** [review]
Everything looks well!

**Comment by fernandofernandezuy** [comment]
[[Shared-Components] Table](https://trello.com/c/bM5kL00W/79-shared-components-table)

**Review by ghost — APPROVED** [review]
ok for me!

**Review by ghost — APPROVED** [review]
ok for me!

**Comment by marcohzo** [comment]
Everything is in order

**Review by AleMac17 — APPROVED** [review]

**Comment by nazarenapantanetti** [comment]
Tested and approved. Good job, all the tables have consistency!

**Pull request merged**
