### PR TITLE
BaSP-MR-191: Firebase log in

### PR DESCRIPTION
**Pull request by Federico-Peralta**
- Create the necessary logic to request the creation of a token to the Login file.
- Spread the token on the routes

### CODE REVIEW

**Review by fernandofernandezuy — APPROVED** [review]
Good job!

**Review by lorenzomauro59 — APPROVED** [review]
Good job Fede!

**Comment by Federico-Peralta** [comment]
[[Log-in] Firebase logic](https://trello.com/c/B4EoizJO/191-log-in-firebase-logic)

**Comment by nazarenapantanetti** [comment]
Tested in master, come changes were request. Follow the link for details https://trello.com/c/w4Q2MyTK/230-login-bug-password-input-is-untidy

**Pull request merged**
