### PR TITLE
BaSP-MR-62: Form edit create members added

### PR DESCRIPTION
**Pull request by Gonzarey96**
Added all missing functionalities, the edit member and create member form.

### CODE REVIEW

**Review by lorenzomauro59 — COMMENTED** [review]
You should change the index.js Form name to index.jsx

**Comment by Gonzarey96** [comment]
[[Members] Add/Edit Form](https://trello.com/c/ikwmmsjh/62-members-add-edit-form)

**Review by lorenzomauro59 — APPROVED** [review]
Everything looks good!!

**Review by fernandofernandezuy — APPROVED** [review]
Seems good to me!

**Review by LucianoAlarcon — APPROVED** [review]

**Pull request merged**
